apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: huggingface-token-external-secret
  namespace: {{ .Values.global.gaudillm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: hf-token-secret
    template:
      type: Opaque
  data:
  - secretKey: huggingface
    remoteRef:
      key: {{ .Values.hftokensecret.key }}
      property: secret
