apiVersion: v1
kind: ConfigMap
metadata:
  name: create-rhoai-istio-rootca-cert-secret
  namespace: {{ .Values.global.gaudillm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-rhoai-istio-rootca-cert-secret.sh: |
    #!/bin/bash
    EXISTS=$(oc get secret --ignore-not-found rhoai-ca-bundle)

    if [[ -z "${EXISTS}" ]]; then    
      oc create secret generic -n {{ .Values.global.gaudillm.namespace }} rhoai-ca-bundle --from-literal=tls.crt="$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=tls.crt)"
    else
      echo "oc get secret --ignore-not-found rhoai-ca-bundle returned non-empty string, not creating a secret"
    fi
