apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"dataprep-redis:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"dataprep-redis-server\")].image"}]'
  labels:
    io.kompose.service: dataprep-redis
  name: dataprep
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dataprep-redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/chatqna-default: "true"
        io.kompose.service: dataprep-redis
    spec:
      containers:
        - env:
            - name: HOME
              value: /tmp/temp-data
            - name: PYTHONPATH
              value: /home/user/.local/lib/python3.11/site-packages:/home/user
            - name: REDIS_URL
              value: redis://redis-vector-db.gaudi-llm.svc.cluster.local:6379
            - name: INDEX_NAME
              value: rag-redis
            {{- if .Values.global.gaudillm.runtime_envs }}
            {{- range .Values.global.gaudillm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          image: {{ .Values.global.gaudillm.dataprep.image }}
          name: dataprep-redis-server
          ports:
            - containerPort: 6007
              protocol: TCP
          volumeMounts:
            - name: temp-data
              mountPath: /tmp/temp-data
            - name: uploaded-files
              mountPath: /home/user/comps/dataprep/redis/langchain/uploaded_files
      restartPolicy: Always
      volumes:
        - name: temp-data
          emptyDir: {}
        - name: uploaded-files
          emptyDir: {}
