apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/sync-wave: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"tei-gaudi:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"tei-embedding-gaudi-server\")].image"}]'
  labels:
    io.kompose.service: tei-embedding-service
  name: tei-embedding-service
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tei-embedding-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/chatqna-default: "true"
        io.kompose.service: tei-embedding-service
    spec:
      containers:
        - args:
            - --model-id
            - {{ .Values.global.gaudillm.tei_embedding.model_id }}
            - --port
            - "8090"
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  key: huggingface
                  name: hf-token-secret
            - name: OMPI_MCA_btl_vader_single_copy_mechanism
              value: none
            #- name: RUNTIME
            #  value: habana
            - name: HOME
              value: /tmp/temp-data
            {{- if .Values.global.gaudillm.runtime_envs }}
            {{- range .Values.global.gaudillm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          image: {{ .Values.global.gaudillm.tei_embedding.image }}
          name: tei-embedding-gaudi-server
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              habana.ai/gaudi: "1"
            requests:
              habana.ai/gaudi: "1"
          volumeMounts:
            - mountPath: /data
              name: tei-embedding-service-claim0
            - mountPath: /dev/shm
              name: shm
            - name: temp-data
              mountPath: /tmp/temp-data
      restartPolicy: Always
      volumes:
        - name: tei-embedding-service-claim0
          persistentVolumeClaim:
            claimName: tei-embedding-service-claim0
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: temp-data
          emptyDir: {}
