kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: tei-gaudi
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "tei-gaudi:latest"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    git:
      ref: {{ .Values.global.gaudillm.tei_embedding.git_ref }}
      uri: https://github.com/huggingface/tei-gaudi.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile-hpu
      {{- if .Values.global.gaudillm.build_envs }}
      env:
      {{- range .Values.global.gaudillm.build_envs }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
  triggers:
  - type: ConfigChange
