apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: tei-embedding-service-claim0
  name: tei-embedding-service-claim0
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.gaudillm.tei_embedding.pvc.size }}
