apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: redis-vector-db
  name: redis-vector-db
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: redis-vector-db
