global: 
  pattern: gaudillm

  gaudillm:
    namespace: gaudi-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []

    tei_xeon:
      image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.2
      pvc:
        size: 3Gi
      model_id: BAAI/bge-reranker-base
