apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-vault
  namespace: {{ .Values.job.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-210"
data:
  wait-for-vault.sh: |
    #!/bin/bash

    waiting_time=10
    
    until [[ $(oc get ns vault) ]]
    do
      sleep ${waiting_time}
    done

    until [[ $(oc -n vault get pods vault-0 -o jsonpath='{.metadata.name}') == *"vault-0"* ]]
    do
      sleep ${waiting_time}
    done
    
    sleep ${waiting_time}