apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-200"
  name: job-wait-for-vault
  namespace: {{ .Values.job.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
           '/tmp/wait-for-vault.sh' && \
           oc -n vault wait --for=condition=Ready pod/vault-0
        name: wait-for-vault
        volumeMounts:
          - mountPath: /tmp/wait-for-vault.sh
            name: wait-for-vault
            subPath: wait-for-vault.sh
      volumes:
        - name: wait-for-vault
          configMap:
            name: wait-for-vault
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 60