apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"llm-tgi:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"llm-tgi-gaudi-server\")].image"}]'
  labels:
    io.kompose.service: llm
  name: llm
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: llm
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/chatqna-default: "true"
        io.kompose.service: llm
    spec:
      containers:
        - command:
          - /bin/bash
          - -c
          - |
            cp /usr/lib/ssl/cert.pem /tmp/bundle.crt && \
            cat /rhoai-ca/tls.crt  | tee -a '/tmp/bundle.crt' && \
            python llm.py
          env:
            - name: HOME
              value: /tmp/temp-data
            - name: PYTHONPATH
              value: /home/user/.local/lib/python3.11/site-packages:/home/user
            - name: HUGGINGFACEHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: huggingface
                  name: hf-token-secret
            - name: SSL_CERT_FILE
              value: /tmp/bundle.crt
            - name: TGI_LLM_ENDPOINT
              value: https://{{ .Values.global.gaudillm.servingRuntime.name }}-{{ .Values.global.gaudillm.servingRuntime.namespace }}.apps.{{ .Values.global.clusterDomain }}
            {{- if .Values.global.gaudillm.runtime_envs }}
            {{- range .Values.global.gaudillm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          image: {{ .Values.global.gaudillm.llm_server_for_gaudi.image }}
          name: llm-tgi-gaudi-server
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: temp-data
              mountPath: /tmp/temp-data
            - name: odh-ca-bundle
              mountPath: /rhoai-ca
      restartPolicy: Always
      volumes:
        - name: temp-data
          emptyDir: {}
        - name: odh-ca-bundle
          secret:
            secretName: rhoai-ca-bundle
            defaultMode: 420
