apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-mcp-update
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
data:
  wait-for-mcp.sh: |
    #!/bin/bash
    MC_FW_PATH='{{ .Values.machineconfigName.fwpath }}'
    waiting_time=10

    until [[ $(oc get mcp worker -o jsonpath='{.status.configuration.source[*].name}') == *"${MC_IOMMU}"* || $(oc get mcp worker -o jsonpath='{.status.configuration.source[*].name}') == *"${MC_FW_PATH}"* ]]
    do
      sleep ${waiting_time}
    done
    sleep ${waiting_time}
  