apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
  name: job-wait-for-mcp-update
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
           '/tmp/wait-for-mcp.sh' && \
           oc wait mcp/worker --for condition=updated --timeout=2000s
        name: wait-for-mcp-update
        volumeMounts:
          - mountPath: /tmp/wait-for-mcp.sh
            name: wait-for-mcp-update
            subPath: wait-for-mcp.sh
      volumes:
        - name: wait-for-mcp-update
          configMap:
            name: wait-for-mcp-update
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 60