global: 
  pattern: gaudillm

  gaudillm:
    namespace: gaudi-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []
    
    redis_vector_db:  
      image: redis/redis-stack:7.2.0-v9
      pvc:
        size: 3Gi
