config:
   devicePlugin:
     image: vault.habana.ai/docker-k8s-device-plugin/docker-k8s-device-plugin
     version: 1.15.1
   driver:
     image: image-registry.openshift-image-registry.svc:5000/habana-ai-operator/habana-ai-driver
     version: 1.15.1-15
   habanaRuntime:
     image: vault.habana.ai/habana-ocp-operator/1.15.1/habana-runtime
     version: 1.15.1-15
   nodeMetrics:
     image: vault.habana.ai/gaudi-metric-exporter/metric-exporter
     version: 1.15.1-15

habanacheckjob:
  image: vault.habana.ai/gaudi-docker/1.15.1/rhel9.2/habanalabs/pytorch-installer-2.2.0:latest

machineconfigName:
  fwpath: 99-worker-kernel-args-firmware-path

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
  namespace: habana-ai-operator

serviceAccountName: mcp-habana-config-sa
rbac:
  roles:
    - name: habana-config-role
      createRole: true
      apiGroups:
        - '""'
        - '"apps"'
        - '"apiextensions.k8s.io"'
        - '"machineconfiguration.openshift.io"'
        - '"imageregistry.operator.openshift.io"'
      scope:
        cluster: true
      resources:
        - machineconfigs
        - machineconfigpools
        - pods
        - namespaces
        - services
        - configs
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
        - "create"
        - "watch"
  roleBindings:
    - name: habana-config-rolebinding
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: mcp-habana-config-sa
        namespace: habana-ai-operator
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: habana-config-role
