apiVersion: v1
kind: ConfigMap
metadata:
  name: create-s3-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-s3-secret.sh: |
    #!/bin/bash
    if [[ $(oc -n openshift-storage get secret s3-secret-bck) ]]; then
      echo "SECRET EXISTS"
    else
      echo "CREATING SECRET..."
      oc create secret generic s3-secret-bck -n {{ .Values.global.namespace }} \
      --from-literal=AWS_ACCESS_KEY_ID=$(oc extract -n openshift-storage secret/rook-ceph-object-user-ocs-storagecluster-cephobjectstore-ocs-storagecluster-cephobjectstoreuser --keys=AccessKey --to=-) \
      --from-literal=AWS_SECRET_ACCESS_KEY=$(oc extract -n openshift-storage secret/rook-ceph-object-user-ocs-storagecluster-cephobjectstore-ocs-storagecluster-cephobjectstoreuser --keys=SecretKey --to=-) \
      --from-literal=S3_RGW_ROUTE=$(oc -n openshift-storage get route {{ .Values.route.name }} -ojsonpath='{.spec.host}')
    fi
