apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
  name: create-s3-bucket
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.awsimage }}
        command:
        - /bin/bash
        - -c
        - |
          aws --endpoint https://${S3_RGW_ROUTE} --no-verify-ssl s3api create-bucket --bucket {{ .Values.rgw.bucketName }}
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY_ID
                name: s3-secret-bck
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_ACCESS_KEY
                name: s3-secret-bck
          - name: S3_RGW_ROUTE
            valueFrom:
              secretKeyRef:
                key: S3_RGW_ROUTE
                name: s3-secret-bck
        name: create-s3-bucket
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
