apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: tei-xeon-service
  name: tei-xeon-service
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  ports:
    - name: "8808"
      port: 8808
      targetPort: 8080
  selector:
    io.kompose.service: tei-xeon-service
